# Generated by Django 5.0.4 on 2024-06-06 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='capacidad_máxima',
            new_name='capacidad_maxima',
        ),
        migrations.RenameField(
            model_name='clase',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='entrenador',
            old_name='número_de_teléfono',
            new_name='numero_de_telefono',
        ),
        migrations.RenameField(
            model_name='equipodeportivo',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_inicio_membresia',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='membresia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.membresia'),
        ),
    ]
