# Generated by Django 5.0.4 on 2024-06-06 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_capacidad_máxima_clase_capacidad_maxima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_inicio_membresia',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
