# Generated by Django 5.0.4 on 2024-05-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_options_remove_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membresía',
            new_name='Membresia',
        ),
    ]
