# Generated by Django 5.0.4 on 2024-05-19 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_membresía_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='membresia',
            field=models.ForeignKey(choices=[(1, 'Membresia Básica'), (2, 'Membresia Plus'), (3, 'Membresia Premium')], default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.membresia'),
        ),
    ]
