# Generated by Django 5.0.4 on 2024-06-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_membresia_precio_mensual_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
