# Generated by Django 5.0.4 on 2024-06-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
