# Generated by Django 5.0.4 on 2024-05-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_membresia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membresia',
            old_name='duración',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='membresia',
            old_name='tipo_de_membresía',
            new_name='tipo_de_membresia',
        ),
    ]
