# Generated by Django 5.0.4 on 2024-05-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_duración_membresia_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='membresia',
            field=models.ForeignKey(choices=[(1, 'Membresia Básica'), (2, 'Membresia Plus'), (3, 'Membresia Premium')], default=3, on_delete=django.db.models.deletion.CASCADE, to='api.membresia'),
        ),
    ]
