# Generated by Django 5.0.4 on 2024-05-19 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_entrenador_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='equipodeportivo',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='clase',
            name='nombre_clase',
            field=models.CharField(choices=[(1, 'Clase de Boxeo'), (2, 'Clase de Musculación'), (3, 'Clase de Zumba'), (4, 'Clase de Yoga'), (5, 'Clase de Pilates')], default=2, max_length=100),
        ),
        migrations.AlterField(
            model_name='clase',
            name='capacidad_máxima',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='equipodeportivo',
            name='nombre',
            field=models.CharField(choices=[(1, 'Equipo de Boxeo'), (2, 'Equipo de Musculación'), (3, 'Equipo de Zumba'), (4, 'Equipo de Yoga'), (5, 'Equipo de Pilates')], default=2, max_length=100),
        ),
    ]
