# Generated by Django 5.0.4 on 2024-05-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_clase_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='horario',
        ),
    ]
