# Generated by Django 5.0.4 on 2024-05-30 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_clase_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaclase',
            name='hora_de_entrada',
        ),
        migrations.RemoveField(
            model_name='reservaclase',
            name='hora_de_salida',
        ),
        migrations.AddField(
            model_name='reservaclase',
            name='horario',
            field=models.CharField(default=django.utils.timezone.now),
        ),
    ]
