# Generated by Django 5.0.4 on 2024-05-30 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_reservaclase_hora_de_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaclase',
            name='fecha',
            field=models.CharField(default=django.utils.timezone.now),
        ),
    ]
